### ISSUE TITLE
"curl" command in windows OS is not support!

### ISSUE THREAD

**Issue by hoipo** [filow/gulp_h5packer#1]
you use the spawn process to request the url for getting content of file,but it just can work in linux or Mac,please fix it! thanks.

**Comment by filow** [comment]
I feel sorry about using that hack way, i'll fix it soon

**Comment by filow** [comment]
This version of gulp_h5packer is just a experimental project, and is not recommended for production use.  But if you need, i'll rewrite this project for you.

**Comment by hoipo** [comment]
I use the modole "sync-request" to replace the "curl" command, it works! I will fork it and fix it soon.

**Comment by filow** [comment]
Yesterday i fixed it with module "request", and refactoring it to async way. You may try it first. Tip: You can update with "npm update gulp_h5packer" On 2015-12-16 10:44 , hoipo Wrote: I use the modole "sync-request" to replace the "curl" command, it works! I will fork it and fix it soon. — Reply to this email directly or view it on GitHub.

**Comment by hoipo** [comment]
OK, thanks
