### ISSUE TITLE
unifyUrl.js中的line:21中的监听无效

### ISSUE THREAD

**Issue by hoipo** [filow/gulp_h5packer#2]
你好，又是我，unifyUrl.js中的line:21中的监听无效，cb函数并没有执行

**Comment by filow** [comment]
你是真的要用在项目里么？我这个项目其实也就是个练手的东西。如果真的要用的话我可以花点时间重构一下。现在的架构还是偏向于同步风格，我可以改成异步的。

**Comment by filow** [comment]
刚才改了一下，感觉还是必须得改成异步的风格才能比较富有拓展性

**Comment by hoipo** [comment]
我最近在做一个前端H5的构建和优化工具，看到你的这个gulp插件很不错，就拿来尝试了，我fork了，我尝试自己也重构一下看看

**Comment by filow** [comment]
这个插件是练手作品，我这边还有个更完整的，不过不再是插件了，是个完整的工具，你要不？

**Comment by hoipo** [comment]
好啊好啊，可以拿来研究研究，tszhanghb@outlook.com   非常感谢
